### ISSUE TITLE
Tuesday goals

### ISSUE THREAD

**Issue by marisid** [NodeGroup2/OCD-B#11]
- [x] Create project folder structure (`src`, `public`, `views` and `tests`) #3
- [x] Set up local database (empty) with superuser *admin* #4
- [x] Create `config.env` file #5
- [x] Write `build_db.sql` file to create `users` table and add a few users #7
- [x] Static html files (2) under public folder for login and register pages #6
- [x] Set up Hapi server and basic routes for login and register #8
