### ISSUE TITLE
Stretch goals

### ISSUE THREAD

**Issue by marisid** [NodeGroup2/OCD-B#26]
- [ ] Redirect to a new html page after successful user registration (instead of redirecting to login page) #22
- [ ] Show average rating next to resources list
- [x] Use stars to show rating instead of numbers
- [ ] Replace static html files with dynamic files #25
- [ ] When user registers, check if username already exists
- [ ] Add logout button #30
