### ISSUE TITLE
Thursday goals

### ISSUE THREAD

**Issue by marisid** [NodeGroup2/OCD-B#33]
- [x] Update README with instructions on building a database #42 
- [x] Create template for user account page: my reviews #20
- [x] Create template for review form #20
- [x] Add styling to user page #20
- [x] Add styling to review form #20
- [x] Connect review form with back-end #39
